# Generated by Django 5.0.3 on 2024-03-15 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_alter_agency_users_alter_branch_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the constant')),
                ('current_fiscal', models.CharField(max_length=10, verbose_name='Fiscal year')),
                ('next_bill_number', models.IntegerField(default=1, verbose_name='Next bill Number')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.agency')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.branch')),
            ],
        ),
    ]
