# Generated by Django 5.0.3 on 2024-05-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billnumber',
            name='current_fiscal',
        ),
        migrations.AddField(
            model_name='billnumber',
            name='format',
            field=models.CharField(default='__fy_1__-__fy_2__-__number__', verbose_name='Bill Number Format'),
        ),
        migrations.AddField(
            model_name='billnumber',
            name='fy_1',
            field=models.CharField(default=24, max_length=4, verbose_name='Fiscal year 1'),
        ),
        migrations.AddField(
            model_name='billnumber',
            name='fy_2',
            field=models.CharField(default=25, max_length=4, verbose_name='Fiscal year 2'),
        ),
    ]
