# Generated by Django 5.0.3 on 2024-03-11 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_alter_agency_users_alter_branch_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name of the account')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current Balance')),
                ('short', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Account Short')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.agency')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.branch')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name of the label')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.agency')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the payment method')),
                ('account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.agency')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.branch')),
            ],
        ),
        migrations.CreateModel(
            name='AccountLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=500, verbose_name='Description of the transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount of transaction')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance before')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance After')),
                ('date', models.DateTimeField(verbose_name='Timestamp')),
                ('link', models.CharField(blank=True, max_length=50, null=True, verbose_name='Linked To')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('labels', models.ManyToManyField(to='accounts.paymentlabel')),
                ('method', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.paymentmethod')),
            ],
        ),
    ]
