# Generated by Django 5.0.3 on 2024-03-12 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0002_alter_agency_users_alter_branch_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlabel',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.branch'),
            preserve_default=False,
        ),
    ]
