# Generated by Django 5.0.3 on 2024-03-12 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_paymentlabel_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
