# Generated by Django 5.0.3 on 2024-03-11 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('store', '0002_alter_agency_users_alter_branch_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierBillExtraExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Amount')),
                ('tax_incl', models.BooleanField(default=False, verbose_name='Is Tax Inclusive?')),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cgst')),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Sgst')),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Igst')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Amount (after taxes)')),
            ],
        ),
        migrations.CreateModel(
            name='InitialStockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('ref', models.CharField(max_length=300, verbose_name='Reference')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.agency')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.branch')),
                ('products', models.ManyToManyField(to='products.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of the supplier')),
                ('number', models.CharField(max_length=20, verbose_name='Number of the supplier')),
                ('address', models.CharField(max_length=200, verbose_name='Address of the supplier')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current Balance')),
                ('state', models.CharField(default='UTTAR PRADESH - 09', max_length=50, verbose_name='State')),
                ('gstin', models.CharField(blank=True, default='', max_length=20, verbose_name='GSTIN')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.agency')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.branch')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=200, verbose_name='remarks')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance Before')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance after')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('date', models.DateTimeField()),
                ('link', models.CharField(blank=True, max_length=50, null=True, verbose_name='Linked To')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Bill Number')),
                ('date', models.DateTimeField()),
                ('received_status', models.BooleanField(default=True, verbose_name='Are the products received')),
                ('cash_discount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cash Discount')),
                ('cash_discount_type', models.CharField(choices=[('Percentage', 'percentage'), ('Amount', 'amount')], default='percentage', max_length=10, verbose_name='Type of cash discount')),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cgst')),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sgst')),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Igst')),
                ('buying_price_gst_incl', models.BooleanField(default=False, verbose_name='is buying price of products inclusive of gst?')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('payable', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Payable')),
                ('products', models.ManyToManyField(to='products.productitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
                ('extra_expenses', models.ManyToManyField(to='suppliers.supplierbillextraexpenses')),
                ('ledger', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplierledger')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Return Number')),
                ('date', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('roundoff', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='roundoff')),
                ('remarks', models.CharField(max_length=300, verbose_name='Remarks')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.agency')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.branch')),
                ('products', models.ManyToManyField(to='products.productitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
                ('ledger', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplierledger')),
            ],
        ),
    ]
