# Generated by Django 5.0.3 on 2024-03-11 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_alter_agency_users_alter_branch_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the customer')),
                ('number', models.CharField(max_length=20, verbose_name='number of the customer')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='address of the customer')),
                ('gstin', models.CharField(blank=True, max_length=100, null=True, verbose_name='gstin of the customer')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance')),
                ('state', models.CharField(default='UTTAR PRADESH - 09', max_length=50, verbose_name='State')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.agency')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.branch')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=200, verbose_name='remarks')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance Before')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance after')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
