# Generated by Django 5.0.3 on 2024-03-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerledger',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Linked To'),
        ),
    ]
