# Generated by Django 5.0.3 on 2024-03-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerledger_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='markdown',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Markdown in percentage'),
        ),
    ]
