# Generated by Django 5.0.3 on 2024-05-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='shipping address of the customer'),
        ),
    ]
