# Generated by Django 5.0.3 on 2024-03-11 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '__first__'),
        ('products', '__first__'),
        ('store', '0002_alter_agency_users_alter_branch_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Bill Number')),
                ('date', models.DateTimeField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cgst')),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='sgst')),
                ('igst', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='igst')),
                ('roundoff', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='roundoff')),
                ('payable', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payable')),
                ('use_previous_balance', models.BooleanField(default=True, verbose_name='Use previous balance?')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.agency')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.branch')),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('ledger', models.ManyToManyField(to='customers.customerledger')),
                ('payments', models.ManyToManyField(to='accounts.accountledger')),
                ('products', models.ManyToManyField(to='products.productitem')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Bill Number')),
                ('date', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.agency')),
                ('bill', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.bill')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.branch')),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customerledger')),
                ('products', models.ManyToManyField(to='products.productitem')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
