# Generated by Django 5.0.3 on 2024-03-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payable',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payable = total + previous balance'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total = subtotal + taxes + roundoff'),
        ),
    ]
