# Generated by Django 5.0.3 on 2024-03-15 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_bill_payable_alter_bill_total'),
        ('customers', '0003_customer_markdown'),
        ('products', '0005_alter_productledger_link'),
        ('store', '0002_alter_agency_users_alter_branch_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_converted', models.BooleanField()),
                ('remarks', models.CharField(max_length=200)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.agency')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Delivery Number')),
                ('date', models.DateTimeField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cgst')),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='sgst')),
                ('igst', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='igst')),
                ('roundoff', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='roundoff')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('converted_to', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.bill', verbose_name='Converted to bill')),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_challan', to='customers.customer')),
                ('items', models.ManyToManyField(to='billing.deliverychallanitem')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
