# Generated by Django 5.0.3 on 2024-03-15 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_deliverychallanitem_deliverychallan'),
        ('store', '0002_alter_agency_users_alter_branch_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverychallanitem',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='deliverychallanitem',
            name='branch',
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.agency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.branch'),
            preserve_default=False,
        ),
    ]
