# Generated by Django 5.0.3 on 2024-05-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_deliverychallanitem_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='po_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Bill PO Number'),
        ),
    ]
