# Generated by Django 5.0.3 on 2024-03-11 11:52

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_alter_agency_users_alter_branch_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the category')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.agency')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('unit', models.CharField(choices=[('pc', 'pc'), ('m', 'm')], max_length=2, verbose_name='Unit')),
                ('hsn', models.CharField(default='520811', max_length=100, verbose_name='hsn')),
                ('default_selling_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Selling price')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Current Stock')),
                ('default_tax', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Tax Percentage')),
                ('finished', models.BooleanField(verbose_name='Is this a finished product or an in progress product')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.agency')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.branch')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=13, verbose_name='UUID of the product')),
                ('status', models.CharField(choices=[('SOLD', 'SOLD'), ('UNSOLD', 'UNSOLD'), ('AWAITED', 'AWAITED'), ('RETURNED', 'RETURNED')], default='UNSOLD', max_length=8, verbose_name='Status of the product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Selling price')),
                ('size', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Size of the packet size in g')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Discount')),
                ('tax', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Tax Percentage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('remarks', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bal_before', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bal_after', models.DecimalField(decimal_places=2, max_digits=6)),
                ('link', models.CharField(blank=True, max_length=50, null=True, verbose_name='Linked To')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage of this product needed')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='recipe',
            field=models.ManyToManyField(blank=True, related_name='ingredient', to='products.recipeingredient'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the subcategory')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.agency')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_name_category'),
        ),
    ]
