# Generated by Django 5.0.3 on 2024-03-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='bulk',
            field=models.BooleanField(default=False, verbose_name='Is this product sold in bulk'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_pieces',
            field=models.BooleanField(default=True, verbose_name='Is product sold in quantity or pieces'),
            preserve_default=False,
        ),
    ]
