# Generated by Django 5.0.3 on 2024-03-14 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_unit_product_bulk_product_is_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='original_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Original Size of the packet in g'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productitem',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productitem',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Current Size of the packet in g'),
        ),
    ]
