# Generated by Django 5.0.3 on 2024-03-14 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productitem_original_size_productitem_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productitem'),
        ),
    ]
