# Generated by Django 5.0.3 on 2024-03-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productitem_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productledger',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Linked To'),
        ),
    ]
