# Generated by Django 5.0.3 on 2024-03-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productledger_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productledger',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='productledger',
            name='bal_after',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='productledger',
            name='bal_before',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
