# Generated by Django 5.0.3 on 2024-03-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productledger_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='original_size',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Original Size of the packet in g'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Current Size of the packet in g'),
        ),
    ]
