# Generated by Django 5.0.3 on 2024-05-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productitem_original_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Cost price'),
        ),
    ]
